/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music;

import com.formdev.flatlaf.FlatLightLaf;
import jaco.mp3.player.MP3Player;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Niwa / Kurniawan - 205314148
 */
public class Main extends javax.swing.JFrame {

    QueueL daftarLagu = new QueueL();
    QueueL daftarAntrian = new QueueL();
    String namaLagu;
    MP3Player player;
    File songFile;
    String currentPath;
    String imagePath;
    int playedIndex;

    /**
     * Creates new form Player
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        judulLagu.setText("");
        player = new MP3Player();
        playedIndex = 0;
        DefaultTableModel tabelLaguAntrian = new DefaultTableModel();
        tabelLaguAntrian.addColumn("Judul");
        TabelAntrian.setModel(tabelLaguAntrian);
        refreshTableDaftarLagu();
    }

    public void refreshTableDaftarLagu() {
        TableModel tabelPlayer = new TableModel(daftarLagu);
        TabelDaftar.setModel(tabelPlayer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfCariLAgu = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDaftar = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        TambahLagu = new javax.swing.JButton();
        HapusLagu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TambahAntrian = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelAntrian = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int col) {
                Component comp = super.prepareRenderer(renderer, row, col);
                if (row > playedIndex) {
                    comp.setBackground(Color.GRAY);
                }else if(row == playedIndex){
                    comp.setBackground(Color.RED);
                }else{
                    comp.setBackground(Color.WHITE);
                }
                return comp;
            }
        };
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        judulLagu = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Stop = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Play = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Player");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Cari Lagu : ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfCariLAgu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCariLAgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.add(jPanel7);

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel4.add(cari);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR LAGU ");
        jPanel5.add(jLabel1, java.awt.BorderLayout.NORTH);

        TabelDaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelDaftar);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        TambahLagu.setText("TAMBAH");
        TambahLagu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahLaguActionPerformed(evt);
            }
        });
        jPanel6.add(TambahLagu);

        HapusLagu.setText("HAPUS");
        HapusLagu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusLaguActionPerformed(evt);
            }
        });
        jPanel6.add(HapusLagu);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        TambahAntrian.setText("TAMBAH DALAM ANTRIAN");
        TambahAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahAntrianActionPerformed(evt);
            }
        });
        jPanel2.add(TambahAntrian, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ANTRIAN LAGU");
        jPanel8.add(jLabel2, java.awt.BorderLayout.NORTH);

        TabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelAntrian.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(TabelAntrian);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel11.setLayout(new java.awt.BorderLayout());

        judulLagu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        judulLagu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLagu.setText("JUDUL");
        jPanel11.add(judulLagu, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel9.add(jPanel11, gridBagConstraints);

        Stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.png"))); // NOI18N
        Stop.setBorderPainted(false);
        Stop.setContentAreaFilled(false);
        Stop.setDefaultCapable(false);
        Stop.setPreferredSize(new java.awt.Dimension(40, 40));
        Stop.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop_off.png"))); // NOI18N
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        Next.setBorderPainted(false);
        Next.setContentAreaFilled(false);
        Next.setFocusPainted(false);
        Next.setPreferredSize(new java.awt.Dimension(40, 40));
        Next.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next_off.png"))); // NOI18N
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        Play.setBorderPainted(false);
        Play.setContentAreaFilled(false);
        Play.setFocusPainted(false);
        Play.setPreferredSize(new java.awt.Dimension(40, 40));
        Play.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play_off.png"))); // NOI18N
        Play.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause.png"))); // NOI18N
        Play.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PlayItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel9.add(jPanel10, gridBagConstraints);

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HapusLaguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusLaguActionPerformed
        if (!TabelDaftar.getSelectionModel().isSelectionEmpty()) {
            int row = TabelDaftar.getSelectedRow();
            daftarLagu.getAntrian().remove(daftarLagu.getAntrian().baca(row));
            refreshTableDaftarLagu();
        }
    }//GEN-LAST:event_HapusLaguActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        String katakunci = tfCariLAgu.getText().toLowerCase();
        for (int i = 0; i < TabelDaftar.getRowCount(); i++) {
            String judul = String.valueOf(TabelDaftar.getValueAt(i, 0)).toLowerCase();
            String banding = judul.replaceAll(katakunci, "");
            if (!judul.equals(banding)) {
                TabelDaftar.setRowSelectionInterval(i, i);
                break;
            }
        }
    }//GEN-LAST:event_cariActionPerformed

    private void TambahLaguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahLaguActionPerformed
        String currentDirectory = System.getProperty("user.home") + System.getProperty("file.separator") + "Music";
        JFileChooser openFileChooser = new JFileChooser(currentDirectory);
        openFileChooser.setMultiSelectionEnabled(true);
        openFileChooser.setFileFilter(new FileTypeFilter(".mp3", "Open MP3 Files Only!"));
        int result = openFileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File[] songFile = openFileChooser.getSelectedFiles();
            for (File song : songFile) {
                daftarLagu.enqueue(song);
            }
        }
        refreshTableDaftarLagu();
    }//GEN-LAST:event_TambahLaguActionPerformed

    private void TambahAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahAntrianActionPerformed
        if (!TabelDaftar.getSelectionModel().isSelectionEmpty()) {
            int[] rows = TabelDaftar.getSelectedRows();
            for (int row : rows) {
                tampilAntrian(daftarLagu.get(row));
                playedIndex++;
            }
        }
    }//GEN-LAST:event_TambahAntrianActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        try {
            File songFile = daftarAntrian.dequeue();
            player.addToPlayList(songFile);
            judulLagu.setText(songFile.getName());
            Play.setSelected(true);
            player.skipForward();
            repaint();
            playedIndex--;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak ada lagu di dalam antrian");
        }
    }//GEN-LAST:event_NextActionPerformed

    private void PlayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PlayItemStateChanged
        if (Play.isSelected()) {
            try {
                if (player.getPlayList().isEmpty()) {
                    NextActionPerformed(null);
                }
                player.play();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tidak ada lagu di dalam antrian");
            }
        } else {
            try {
                player.pause();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_PlayItemStateChanged

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        player.stop();
        Play.setSelected(false);
        judulLagu.setText("");
    }//GEN-LAST:event_StopActionPerformed

    private void tampilAntrian(File songFile) {
        String[] column = {"Judul"};
        Object[][] data = new Object[TabelAntrian.getRowCount() + 1][column.length];
        if (daftarAntrian.isEmpty()) {
            data[0][0] = songFile.getName();
        } else {
            int tabelIndex = TabelAntrian.getRowCount();
            int i = data.length - 1;
            while (i > 0) {
                data[i--][0] = TabelAntrian.getValueAt(--tabelIndex, 0);
            }
            data[i][0] = songFile.getName();
        }
        DefaultTableModel antrian = new DefaultTableModel(data, column);
        TabelAntrian.setModel(antrian);
        daftarAntrian.enqueue(songFile);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusLagu;
    private javax.swing.JButton Next;
    private javax.swing.JToggleButton Play;
    private javax.swing.JButton Stop;
    private javax.swing.JTable TabelAntrian;
    private javax.swing.JTable TabelDaftar;
    private javax.swing.JButton TambahAntrian;
    private javax.swing.JButton TambahLagu;
    private javax.swing.JButton cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulLagu;
    private javax.swing.JTextField tfCariLAgu;
    // End of variables declaration//GEN-END:variables
}
